name: Gatsby Publish

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [content_change]

jobs:
  build:
    name: Deploy to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Install ffmpeg
        run: sudo apt-get install -y ffmpeg
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Install and build
        run: |
          npm ci
          npm run build -- --prefix-paths
        env:
          MAILCHIMP_ENDPOINT: ${{secrets.MAILCHIMP_ENDPOINT}}
      - name: Run tests
        run: npm test
        env:
          CI: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
