name: Pull Request

on:
  pull_request:
    branches:
      - "master"

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: apt helper action
        # You may pin to the exact commit or the version.
        # uses: ryankurte/action-apt@854f019356a19d5b1537e1e4496fe29a643189c2
        uses: ryankurte/action-apt@v0.1.0
        with:
          # apt packages to install
          packages: ffmpeg
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: "13.11"

      - name: Install modules
        run: npm i

      - name: Run unit tests
        run: npm run test

      - name: Build and export
        run: npm run build
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{secrets.CONTENTFUL_ACCESS_TOKEN}}
          CONTENTFUL_SPACE_ID: ${{secrets.CONTENTFUL_SPACE_ID}}
          MAILCHIMP_ENDPOINT: ${{secrets.MAILCHIMP_ENDPOINT}}

      - name: Run cypress end-to-end tests
        run: mkdir -p cypress/screenshots && npm run test-e2e
        env:
          ROOT_URL_DOMAIN: localhost

      - name: Upload cypress screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload cypress videos
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

      - name: Accessibility check
        run: npm run a11y
        env:
          ROOT_URL_DOMAIN: localhost

      - name: Upload pa11y screenshots
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: pa11y-screenshots
          path: pa11y-screenshots
